### ISSUE TITLE
【适配请求】抖音网页搜索

### ISSUE THREAD

**Issue by nb5p** [MUTED64/SearchEngineJumpPlus#2]
请求适配抖音网页搜索，地址为：https://www.douyin.com/search/
当前版本显示效果见下图
![CleanShot 2023-05-13 at 13 17 25](https://github.com/MUTED64/SearchEngineJumpPlus/assets/2098464/63239d41-fd11-40df-93eb-9af12f1e9d0b)

**Comment by MUTED64** [comment]
2ee8da9 version 5.31.13 已调整。
